import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          <header className={styles.header}>
            <div className={styles.headerContent}>
              <Link href="/">
                <Image
                  className={styles.androidLogo}
                  src="https://www.gstatic.com/devrel-devsite/prod/vdbb152dfd6ef5e309aa1d261d45f3fd443aed2691cbfba3f9f80f8a4012a0a8f/android/images/lockup.svg"
                  alt="Android Logo"
                  width={129}
                  height={20}
                  priority
                />
              </Link>
              <nav className={styles.mainNav}>
                <a href="/docs" className={styles.navLink}>
                  Guides
                </a>
                <a href="/docs" className={styles.navLink}>
                  Reference
                </a>
                <a href="/docs" className={styles.navLink}>
                  Samples
                </a>
                <a href="/docs" className={styles.navLink}>
                  Downloads
                </a>
              </nav>
            </div>
          </header>

          <main className={styles.main}>
            <div className={styles.sidebar}>
              <nav className={styles.sideNav}>
                <h3>Docs</h3>
                <ul>
                  <li>
                    <a href="/docs" className={styles.active}>
                      Introduction
                    </a>
                  </li>
                  <li>
                    <a href="/docs/context">Passing Context</a>
                  </li>
                  <li>
                    <a href="/docs">First App</a>
                  </li>
                </ul>
                <h3>Core Topics</h3>
                <ul>
                  <li>
                    <a href="/docs">Activities</a>
                  </li>
                  <li>
                    <a href="/docs">Architecture</a>
                  </li>
                  <li>
                    <a href="/docs">UI & Navigation</a>
                  </li>
                </ul>
              </nav>
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
